### PR TITLE
Mark the job runtime plugin config as nullable

### LINKED ISSUE #32: Allow `job_runtime` plugin config to be `null`

### PR DESCRIPTION
**Pull request by tuliren**
## Summary
- Mark `job_runtime` as `nullable`.
- Replace `null` plugin config with empty objects.
- This is necessary because on the server side, we merge all `runtime` into only array. However, if the config is `null`, `deepmerge` will only keep the last value.
  - For example, when merging these objects with a `null` field:
    ```ts
    deepmerge({ a: null }, { a: { runtime: [1] } }, { a: { runtime: [2] } })
    // { a: { runtime: [2] } }
    ```
  - In contrast, when the object is empty:
    ```ts
    deepmerge({ a: {} }, { a: { runtime: [1] } }, { a: { runtime: [2] } })
    // { a: { runtime: [1, 2] } }
    ```
  - We need to keep all the values. So the conversion is necessary.

This PR resolves #32.

### CODE REVIEW

**Review by jrhizor — APPROVED** [review]
It's kind of unfortunate that it needs to be wrapped.

**Comment by tuliren** [comment]
> It's kind of unfortunate that it needs to be wrapped.

The alternative solution is to provide a custom merging function to `deepmerge`. But I think the current solution is good enough, as long as we have clear comments and test cases.

**Comment by tuliren** [comment]
Actually let me just try the custom merging function approach if it is really quick.

**Comment by tuliren** [comment]
After a second thought, I think the current approach is better, because deepmerge is performed both on the server side and in the local mode. If we introduce a custom merging logic, we need to ensure that the logic is consistent in both places. With the current approach, that's not a concern.

**Pull request merged**
